# Change these first
owner: avcga # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Public Website
    url: https://coastguard.com.au
  - name: Members Portal
    url: https://portal.coastguard.com.au
  - name: Helpdesk
    url: https://jira.coastguard.com.au
  - name: SafeTrx
    url: https://safetrx.coastguard.com.au
  - name: Email (Google)
    url: https://mail.google.com
  - name: Database
    url: https://database.coastguard.com.au
assignees: # Users to assign downtime issues (optional)
  - jeremyw24

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.coastguard.com.au
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://coastguard.com.au/wp-content/uploads/2018/05/AVGC-Logo_100-2.png
  name: AVCGA Service Status
  introTitle: "**AVCGA** Service Status"
  introMessage: This site provides real-time service status information regarding AVCGA IT Services available to members, planned and unplanned service outages will be listed below. You can view the current status and updates of any open incidents or planned outages (typically updates and patching). If you are having issues with a service and there is no outage alert you can [**Raise a Helpdesk Ticket**](https://helpdesk.coastguard.com.au)
  navbar:
    - title: Status
      href: /
    - title: CG Helpdesk
      href: https://helpdesk.coastguard.com.au

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
